# Generated by Django 4.0 on 2022-04-25 14:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Physcological_session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='physcological_sessions',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='tg',
        ),
    ]
