# Generated by Django 4.0 on 2022-05-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid', '0002_physcological_session_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=150, unique=True)),
                ('likes', models.IntegerField()),
                ('views', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Psychological_Sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.CharField(max_length=1500)),
                ('diagnosis', models.CharField(max_length=150)),
                ('story', models.CharField(max_length=150)),
                ('feelings', models.CharField(max_length=150)),
                ('link', models.CharField(max_length=150)),
                ('psychologist', models.CharField(max_length=150)),
                ('counselee', models.CharField(max_length=150)),
                ('storage_id_sessions', models.CharField(max_length=150)),
                ('in_session', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='newuser',
            name='ratings',
            field=models.FloatField(default=2.5),
        ),
    ]
